FROM alpine:3.12 as base

RUN apk update &&\
    apk add git

RUN mkdir /db_dump &&\
    git clone https://github.com/datacharmer/test_db &&\
    cp test_db/*.dump /db_dump &&\
    cp test_db/employees.sql /db_dump &&\
    cp test_db/show_elapsed.sql /db_dump
    
FROM mysql:latest

COPY --from=base /db_dump /db_dump

WORKDIR /docker-entrypoint-initdb.d

RUN ln -sfn /db_dump/* /docker-entrypoint-initdb.d